/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CodeOfConductRouteImport } from './routes/code-of-conduct'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EnterpriseApplicationsRouteImport } from './routes/enterprise-applications'
import { Route as GrcAiGovernanceRouteImport } from './routes/grc-ai-governance'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as GrcAiGovernanceIndexRouteImport } from './routes/grc-ai-governance/index'
import { Route as GrcAiGovernanceAiRiskAssessmentRouteImport } from './routes/grc-ai-governance/ai-risk-assessment'
import { Route as GrcAiGovernanceContinuousControlsMonitoringRouteImport } from './routes/grc-ai-governance/continuous-controls-monitoring'
import { Route as GrcAiGovernanceOptroAiPartnershipRouteImport } from './routes/grc-ai-governance/optro-ai-partnership'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfConductRoute = CodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseApplicationsRoute = EnterpriseApplicationsRouteImport.update({
  id: '/enterprise-applications',
  path: '/enterprise-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const GrcAiGovernanceRoute = GrcAiGovernanceRouteImport.update({
  id: '/grc-ai-governance',
  path: '/grc-ai-governance',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const GrcAiGovernanceIndexRoute = GrcAiGovernanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GrcAiGovernanceRoute,
} as any)
const GrcAiGovernanceAiRiskAssessmentRoute =
  GrcAiGovernanceAiRiskAssessmentRouteImport.update({
    id: '/ai-risk-assessment',
    path: '/ai-risk-assessment',
    getParentRoute: () => GrcAiGovernanceRoute,
  } as any)
const GrcAiGovernanceContinuousControlsMonitoringRoute =
  GrcAiGovernanceContinuousControlsMonitoringRouteImport.update({
    id: '/continuous-controls-monitoring',
    path: '/continuous-controls-monitoring',
    getParentRoute: () => GrcAiGovernanceRoute,
  } as any)
const GrcAiGovernanceOptroAiPartnershipRoute =
  GrcAiGovernanceOptroAiPartnershipRouteImport.update({
    id: '/optro-ai-partnership',
    path: '/optro-ai-partnership',
    getParentRoute: () => GrcAiGovernanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/enterprise-applications': typeof EnterpriseApplicationsRoute
  '/grc-ai-governance': typeof GrcAiGovernanceRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/grc-ai-governance/ai-risk-assessment': typeof GrcAiGovernanceAiRiskAssessmentRoute
  '/grc-ai-governance/continuous-controls-monitoring': typeof GrcAiGovernanceContinuousControlsMonitoringRoute
  '/grc-ai-governance/optro-ai-partnership': typeof GrcAiGovernanceOptroAiPartnershipRoute
  '/grc-ai-governance/': typeof GrcAiGovernanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/enterprise-applications': typeof EnterpriseApplicationsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/grc-ai-governance/ai-risk-assessment': typeof GrcAiGovernanceAiRiskAssessmentRoute
  '/grc-ai-governance/continuous-controls-monitoring': typeof GrcAiGovernanceContinuousControlsMonitoringRoute
  '/grc-ai-governance/optro-ai-partnership': typeof GrcAiGovernanceOptroAiPartnershipRoute
  '/grc-ai-governance': typeof GrcAiGovernanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/enterprise-applications': typeof EnterpriseApplicationsRoute
  '/grc-ai-governance': typeof GrcAiGovernanceRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/roadmap': typeof RoadmapRoute
  '/services': typeof ServicesRoute
  '/grc-ai-governance/ai-risk-assessment': typeof GrcAiGovernanceAiRiskAssessmentRoute
  '/grc-ai-governance/continuous-controls-monitoring': typeof GrcAiGovernanceContinuousControlsMonitoringRoute
  '/grc-ai-governance/optro-ai-partnership': typeof GrcAiGovernanceOptroAiPartnershipRoute
  '/grc-ai-governance/': typeof GrcAiGovernanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/code-of-conduct'
    | '/contact'
    | '/enterprise-applications'
    | '/grc-ai-governance'
    | '/privacy-policy'
    | '/roadmap'
    | '/services'
    | '/grc-ai-governance/ai-risk-assessment'
    | '/grc-ai-governance/continuous-controls-monitoring'
    | '/grc-ai-governance/optro-ai-partnership'
    | '/grc-ai-governance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/code-of-conduct'
    | '/contact'
    | '/enterprise-applications'
    | '/privacy-policy'
    | '/roadmap'
    | '/services'
    | '/grc-ai-governance/ai-risk-assessment'
    | '/grc-ai-governance/continuous-controls-monitoring'
    | '/grc-ai-governance/optro-ai-partnership'
    | '/grc-ai-governance'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/code-of-conduct'
    | '/contact'
    | '/enterprise-applications'
    | '/grc-ai-governance'
    | '/privacy-policy'
    | '/roadmap'
    | '/services'
    | '/grc-ai-governance/ai-risk-assessment'
    | '/grc-ai-governance/continuous-controls-monitoring'
    | '/grc-ai-governance/optro-ai-partnership'
    | '/grc-ai-governance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
  ContactRoute: typeof ContactRoute
  EnterpriseApplicationsRoute: typeof EnterpriseApplicationsRoute
  GrcAiGovernanceRoute: typeof GrcAiGovernanceRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RoadmapRoute: typeof RoadmapRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-applications': {
      id: '/enterprise-applications'
      path: '/enterprise-applications'
      fullPath: '/enterprise-applications'
      preLoaderRoute: typeof EnterpriseApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grc-ai-governance': {
      id: '/grc-ai-governance'
      path: '/grc-ai-governance'
      fullPath: '/grc-ai-governance'
      preLoaderRoute: typeof GrcAiGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grc-ai-governance/': {
      id: '/grc-ai-governance/'
      path: '/'
      fullPath: '/grc-ai-governance/'
      preLoaderRoute: typeof GrcAiGovernanceIndexRouteImport
      parentRoute: typeof GrcAiGovernanceRoute
    }
    '/grc-ai-governance/ai-risk-assessment': {
      id: '/grc-ai-governance/ai-risk-assessment'
      path: '/ai-risk-assessment'
      fullPath: '/grc-ai-governance/ai-risk-assessment'
      preLoaderRoute: typeof GrcAiGovernanceAiRiskAssessmentRouteImport
      parentRoute: typeof GrcAiGovernanceRoute
    }
    '/grc-ai-governance/continuous-controls-monitoring': {
      id: '/grc-ai-governance/continuous-controls-monitoring'
      path: '/continuous-controls-monitoring'
      fullPath: '/grc-ai-governance/continuous-controls-monitoring'
      preLoaderRoute: typeof GrcAiGovernanceContinuousControlsMonitoringRouteImport
      parentRoute: typeof GrcAiGovernanceRoute
    }
    '/grc-ai-governance/optro-ai-partnership': {
      id: '/grc-ai-governance/optro-ai-partnership'
      path: '/optro-ai-partnership'
      fullPath: '/grc-ai-governance/optro-ai-partnership'
      preLoaderRoute: typeof GrcAiGovernanceOptroAiPartnershipRouteImport
      parentRoute: typeof GrcAiGovernanceRoute
    }
  }
}

interface GrcAiGovernanceRouteChildren {
  GrcAiGovernanceAiRiskAssessmentRoute: typeof GrcAiGovernanceAiRiskAssessmentRoute
  GrcAiGovernanceContinuousControlsMonitoringRoute: typeof GrcAiGovernanceContinuousControlsMonitoringRoute
  GrcAiGovernanceOptroAiPartnershipRoute: typeof GrcAiGovernanceOptroAiPartnershipRoute
  GrcAiGovernanceIndexRoute: typeof GrcAiGovernanceIndexRoute
}

const GrcAiGovernanceRouteChildren: GrcAiGovernanceRouteChildren = {
  GrcAiGovernanceAiRiskAssessmentRoute: GrcAiGovernanceAiRiskAssessmentRoute,
  GrcAiGovernanceContinuousControlsMonitoringRoute:
    GrcAiGovernanceContinuousControlsMonitoringRoute,
  GrcAiGovernanceOptroAiPartnershipRoute:
    GrcAiGovernanceOptroAiPartnershipRoute,
  GrcAiGovernanceIndexRoute: GrcAiGovernanceIndexRoute,
}

const GrcAiGovernanceRouteWithChildren = GrcAiGovernanceRoute._addFileChildren(
  GrcAiGovernanceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  CodeOfConductRoute: CodeOfConductRoute,
  ContactRoute: ContactRoute,
  EnterpriseApplicationsRoute: EnterpriseApplicationsRoute,
  GrcAiGovernanceRoute: GrcAiGovernanceRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RoadmapRoute: RoadmapRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
